import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import MH from "../components/main-head";
import MF from "../components/main-foot";

const Index: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>home</title>
        <meta name="description" content="Generated by home" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <MH name="Nextjs"></MH>
        <div className={styles.grid}>
          <a href="https://www.nextjs.cn/docs/getting-started" className={styles.card}>
            <h2>快速开始 &rarr;</h2>
            <p>欢迎阅读 Next.js 文档！</p>
          </a>

          <a href="./home" className={styles.card}>
            <h2>安装设置 | 基本特性&rarr;</h2>
            <p>笔记</p>
          </a>
        </div>
      </main>

      <MF></MF>
    </div>
  );
};

export default Index;
